name: Publish to PyPI

on:
  release:
    types: [created]
  push:
    branches: [main]
    paths:
      - 'pyproject.toml'
      - 'yaml_resume_builder/__init__.py'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0)'
        required: true
        default: ''

jobs:
  deploy:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine

      - name: Update version if manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          VERSION="${{ github.event.inputs.version }}"
          # Update version in pyproject.toml
          sed -i "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"$VERSION\"/" pyproject.toml
          # Update version in __init__.py
          sed -i "s/__version__ = \"[0-9]*\.[0-9]*\.[0-9]*\"/__version__ = \"$VERSION\"/" yaml_resume_builder/__init__.py

      - name: Build package
        run: |
          python -m build

      - name: Check package
        run: |
          twine check dist/*

      - name: Verify package name availability
        run: |
          # Extract package name from pyproject.toml
          PACKAGE_NAME=$(grep -m 1 'name = ' pyproject.toml | sed 's/name = "\(.*\)"/\1/')
          echo "Checking availability of package name: $PACKAGE_NAME"

          # Check if package exists on PyPI
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://pypi.org/project/$PACKAGE_NAME/")

          if [ "$HTTP_STATUS" = "200" ]; then
            # Package exists, check if we own it
            echo "Package name '$PACKAGE_NAME' already exists on PyPI."
            echo "Make sure you own this package or choose a different name."
            echo "Continuing with publish step, which will succeed only if you own the package."
          elif [ "$HTTP_STATUS" = "404" ]; then
            echo "Package name '$PACKAGE_NAME' is available on PyPI."
          else
            echo "Unexpected status code: $HTTP_STATUS when checking package name."
            echo "Continuing with publish step."
          fi

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
